server:
  port: 8082
spring:
  datasource:
    # 配置数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wang?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
    filters: stat,wall,log4j
redis:
  host: localhost
  port: 6379
  database: 1
  timeout: 86400
  password:
  pool:
    max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
    max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-idle: 10      # 连接池中的最大空闲连接
    min-idle: 5       # 连接池中的最小空闲连接
token:
  expire:
    seconds: 7200